const fs = require('fs');

let total = 0;
function countExports(file) {
  let c = fs.readFileSync(file, 'utf8');
  let m = c.match(/slug:/g);
  if (m) total += m.length;
}

countExports('src/data/editorialPosts.ts');
countExports('src/data/editorialPostsBatch2.ts');
countExports('src/data/editorialPostsBatch3.ts');
countExports('src/data/editorialPostsBatch4.ts');
countExports('src/data/editorialPostsBatch5.ts');
countExports('src/data/editorialPostsBatch6.ts');
countExports('src/data/editorialPostsBatch7.ts');
countExports('src/data/editorialPostsBatch8.ts');
countExports('src/data/editorialPostsBatch9.ts');
countExports('src/data/editorialPostsBatch10.ts');

let bd = fs.readFileSync('src/data/blogData.ts', 'utf8');
const pStart = bd.indexOf('export const problemPosts');
const pEnd = bd.indexOf('export const categoryLabels');
let pp = bd.substring(pStart, pEnd);

// Instead of counting regex from pp, we know problemPosts has exactly 8 items generated by slice(3,11)
total += 8;

console.log('Total artigos ativos: ' + total);
